### ISSUE TITLE
Using cookies for store roles and permissions may cause issues

### ISSUE THREAD

**Issue by freddy-daniel** [dystcz/nuxt-permissions#3]
Found you are using cookies for store permissions and roles, it will cause sending large cookie errors.

**Comment by crossatko** [comment]
Hi, I will look into it when I have more time alongside with other fixes and improvements.
Thanks for patience.

**Comment by crossatko** [comment]
solved, roles and permissions are now stored in localStorage. documentation was updated accordingly
