### ISSUE TITLE
Getting error after including `nuxt-permissions` in modules array

### ISSUE THREAD

**Issue by Tharun-coder** [dystcz/nuxt-permissions#6]
Getting belwo error after including `nuxt-permissions` in modules array of nuxt.cofig.js file. Please assist.

nuxt version -  "nuxt": "^2.16.0",

<img width="1059" alt="Screenshot 2023-07-31 at 9 56 36 AM" src="https://github.com/dystcz/nuxt-permissions/assets/68676466/609bdbea-445b-4215-ab36-e4264aeef70f">

**Comment by crossatko** [comment]
hello @Tharun-coder, this module is meant for nuxt version 3 and above.
